Fix TypeError: document.querySelectorAll(...).forEach is not a function
Bug: T298910
Change-Id: Iaa67f36278af7805c5d915737d6b30e98b3f8484
(cherry picked from commit d9ef1ad66d9e3a8e7a7387e050e322bdde018ced)