Fix TypeError: trigger.attr is not a function
Code was assuming jQuery.Object when it is now an Element.

Bug: T335148
Change-Id: I4755607f991889468294e022015a6a7e4becbb6c
(cherry picked from commit c61d57c72afb0166212d552d46b937e0642d5319)