Revert "End migration mode"
This reverts commit 40b8558adff476c12cd507ca3e5441d54f18cf1c.

Reason for revert: caused errors in production
   Error: Class 'Vector\SkinVersionLookup' not found

Change-Id: I5faa79f53f288285ae71dea10a33dd7fc62a0baa